### ISSUE TITLE
Doesn't seem to work on MacOS 10.15.7

### ISSUE THREAD

**Issue by 5t0x2fH1z** [melianmiko/zmake#2]
Neither pre-build nor building from source doesn't work for me. In the case of the pre-build app doing nothing when I drug-and-drop watchface folder into the app icon. When I try to run through the console it throws error:
`Error loading Python lib '... zmake.app/Contents/MacOS/Python': dlopen: dlopen(... zmake.app/Contents/MacOS/Python, 10): Symbol not found: _preadv
  Referenced from: ... zmake.app/Contents/MacOS/Python (which was built for Mac OS X 11.0)
  Expected in: /usr/lib/libSystem.B.dylib
 in ...zmake.app/Contents/MacOS/Python`

 In case of building from the source I'm keep getting
 `Traceback (most recent call last):
  File "... zmake/./venv/bin/pyinstaller", line 10, in <module>
    sys.exit(_console_script_run())
  File "... zmake/venv/lib/python3.10/site-packages/PyInstaller/__main__.py", line 194, in _console_script_run
    run()
  File "... zmake/venv/lib/python3.10/site-packages/PyInstaller/__main__.py", line 180, in run
    run_build(pyi_config, spec_file, **vars(args))
  File "... zmake/venv/lib/python3.10/site-packages/PyInstaller/__main__.py", line 61, in run_build
    PyInstaller.building.build_main.main(pyi_config, spec_file, **kwargs)
  File "... zmake/venv/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 971, in main
    build(specfile, distpath, workpath, clean_build)
  File "... zmake/venv/lib/python3.10/site-packages/PyInstaller/building/build_main.py", line 893, in build
    exec(code, spec_namespace)
  File "zmake_darwin.spec", line 27, in <module>
    exe = EXE(
  File "... zmake/venv/lib/python3.10/site-packages/PyInstaller/building/api.py", line 552, in __init__
    self.__postinit__()
  File "... zmake/venv/lib/python3.10/site-packages/PyInstaller/building/datastruct.py", line 173, in __postinit__
    self.assemble()
  File "... zmake/venv/lib/python3.10/site-packages/PyInstaller/building/api.py", line 822, in assemble
    osxutils.sign_binary(build_name, self.codesign_identity, self.entitlements_file)
  File ".. zmake/venv/lib/python3.10/site-packages/PyInstaller/utils/osx.py", line 359, in sign_binary
    raise SystemError(f"codesign command ({cmd_args}) failed with error code {p.returncode}!\noutput: {p.stdout}")
SystemError: codesign command (['codesign', '-s', 'MelianMiko', '--force', '--all-architectures', '--timestamp', '--options=runtime', '... zmake/build/zmake_darwin/zmake']) failed with error code 1!
output: error: The specified item could not be found in the keychain.

Traceback (most recent call last):
  File "... zmake/make_release.py", line 31, in <module>
    shutil.make_archive(f"dist/ZMake_{VERSION}_macos",
  File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 1124, in make_archive
    filename = func(base_name, base_dir, **kwargs)
  File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/shutil.py", line 952, in _make_tarball
    tar.add(base_dir, arcname, filter=_set_uid_gid)
  File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tarfile.py", line 1986, in add
    tarinfo = self.gettarinfo(name, arcname)
  File "/usr/local/Cellar/python@3.10/3.10.9/Frameworks/Python.framework/Versions/3.10/lib/python3.10/tarfile.py", line 1865, in gettarinfo
    statres = os.lstat(name)
FileNotFoundError: [Errno 2] No such file or directory: 'dist/zmake.app'`

**Comment by melianmiko** [comment]
Hi,

This error tells that you don't have a key to sign the bundle. Simply remove [this](https://github.com/melianmiko/zmake/blob/e2f44b5cc18233aaab85a294af1d8967841900f2/zmake_darwin.spec#L41) line, or create a new CodeSign key with that name, and then try to build again.

---

I tried to build my apps under OS X 10.15.x, and that don't worked anyway, due to incompatibility with some Python packages...

**Comment by 5t0x2fH1z** [comment]
> Hi,
> 
> This error tells that you don't have a key to sign the bundle. Simply remove [this](https://github.com/melianmiko/zmake/blob/e2f44b5cc18233aaab85a294af1d8967841900f2/zmake_darwin.spec#L41) line, or create a new CodeSign key with that name, and then try to build again.
> 
> I tried to build my apps under OS X 10.15.x, and that don't worked anyway, due to incompatibility with some Python packages...

right, so no way to build under MacOS?

**Comment by melianmiko** [comment]
> > Hi,
> > This error tells that you don't have a key to sign the bundle. Simply remove [this](https://github.com/melianmiko/zmake/blob/e2f44b5cc18233aaab85a294af1d8967841900f2/zmake_darwin.spec#L41) line, or create a new CodeSign key with that name, and then try to build again.
> > I tried to build my apps under OS X 10.15.x, and that don't worked anyway, due to incompatibility with some Python packages...
> 
> right, so no way to build under MacOS?

I don't know... 

It builds under macOS 11 with Python 3.11 (from homebrew), but I can't get it to work under Mac OS 10.15.x..

**Comment by melianmiko** [comment]
I'll try it again, when will time.
Maybe that try will be luckier.

**Comment by melianmiko** [comment]
Successfully built it on macOS 10.15.7 (VirtualBox) with Python 3.10 from homebrew. Works fine.

Binary build will be available in a few days, as version 1.6.3. Build instruction will be updated too.

**Comment by 5t0x2fH1z** [comment]
Awesome. Thanks for update

**Comment by melianmiko** [comment]
Ready, you can download it from my website, or [via direct link](https://st.melianmiko.ru/zmake/ZMake_v1.6.3_macos.tar.gz).

Please check, now it should work.
